export interface FormGuide {
  /** 一覧表（Excel）での種目名。アプリ側の名前と異なる場合の検索用 */
  aliases: string[];
  primary: string;
  secondary: string;
  setup: string;
  movement: string;
  tips: string;
  mistakes: string[];
  caution: string;
  /** 初心者目安回数（秒数の種目は「秒」表記） */
  reps: string;
  sets: number;
  level: "初級" | "中級";
}

type G = Omit<FormGuide, "mistakes" | "aliases"> & { mistakes: string; aliases?: string[] };

const g = ({ mistakes, aliases = [], ...rest }: G): FormGuide => ({
  ...rest,
  aliases,
  mistakes: mistakes.split("／"),
});

/** 種目キー（SAMPLE_EXERCISES の key）→ フォーム解説 */
export const FORM_GUIDES: Record<string, FormGuide> = {
  dbFloorPress: g({
    primary: "大胸筋",
    secondary: "上腕三頭筋・三角筋前部",
    setup: "床に仰向け。膝を曲げ、ダンベルを胸の横で構える。",
    movement: "肘を床付近まで下ろし、胸の真上へ押し上げる。",
    tips: "肩甲骨を軽く寄せて胸を張る。手首を立て、肘は真横ではなく少し斜め下へ。",
    mistakes: "肘を開きすぎる／腰を反りすぎる／ダンベルをぶつける",
    caution: "肩に鋭い痛みが出る深さまで下げない。",
    reps: "8〜15回",
    sets: 3,
    level: "初級",
  }),
  dbFly: g({
    primary: "大胸筋",
    secondary: "三角筋前部",
    setup: "床に仰向け。腕を胸の上に伸ばし、肘を軽く曲げる。",
    movement: "大きな弧を描くように腕を左右へ開き、胸の力で戻す。",
    tips: "肘の角度をほぼ固定。胸が伸びる範囲までゆっくり下ろす。",
    mistakes: "腕を曲げ伸ばししてプレスになる／下げすぎる",
    caution: "床で肘が止まるため可動域は狭め。肩の違和感があれば中止。",
    reps: "10〜15回",
    sets: 3,
    level: "初級",
  }),
  bbFloorPress: g({
    primary: "大胸筋",
    secondary: "上腕三頭筋・三角筋前部",
    setup: "床に仰向け。連結バーを胸の上で保持。",
    movement: "バーを胸の方向へ下ろし、床に上腕が触れる手前から押し上げる。",
    tips: "左右均等に握る。手首を寝かせず、バーは胸の中央〜やや下へ。",
    mistakes: "左右差／手首が反る／勢いで下ろす",
    caution: "連結部の締め付けと耐荷重を必ず確認。",
    reps: "8〜12回",
    sets: 3,
    level: "中級",
  }),
  pushup: g({
    aliases: ["ノーマルプッシュアップ"],
    primary: "大胸筋",
    secondary: "上腕三頭筋・三角筋前部",
    setup: "手を肩幅より少し広く置き、頭から踵まで一直線。",
    movement: "胸を床へ近づけ、床を押して戻る。",
    tips: "腹と尻に力を入れて体幹を一直線に保つ。胸から下りる意識。",
    mistakes: "腰が落ちる／顔だけ下げる／肘が真横に開く",
    caution: "手首・肩に痛みが出る場合は手幅や角度を調整。",
    reps: "8〜15回",
    sets: 3,
    level: "初級",
  }),
  widePushup: g({
    aliases: ["ワイドプッシュアップ"],
    primary: "大胸筋",
    secondary: "三角筋前部・上腕三頭筋",
    setup: "手を肩幅より広めに置き、体を一直線にする。",
    movement: "胸を床へ下ろして押し戻す。",
    tips: "胸を伸ばす意識。手を広げすぎず、肘は斜め後方へ。",
    mistakes: "手幅を広げすぎる／腰が落ちる",
    caution: "肩前面が痛いなら手幅を狭める。",
    reps: "8〜15回",
    sets: 3,
    level: "初級",
  }),
  narrowPushup: g({
    aliases: ["ナロープッシュアップ", "ナロー／ダイヤモンド腕立て"],
    primary: "上腕三頭筋",
    secondary: "大胸筋・三角筋前部",
    setup: "手を肩幅程度〜少し狭めに置く。",
    movement: "肘を体側に沿わせて体を下ろし、押し上げる。",
    tips: "肘を外へ開かず、脇を締める。",
    mistakes: "肘が外へ逃げる／腰が落ちる",
    caution: "手首や肘に違和感があれば無理に狭めない。",
    reps: "6〜12回",
    sets: 3,
    level: "中級",
  }),
  diamondPushup: g({
    aliases: ["ダイヤモンドプッシュアップ"],
    primary: "上腕三頭筋",
    secondary: "大胸筋",
    setup: "胸の下で親指と人差し指を近づけて手を置く。",
    movement: "肘を曲げて体を下ろし、押し戻す。",
    tips: "肘を体側に沿わせる。きつければ膝つきで実施。",
    mistakes: "手を狭めすぎて手首が痛む／反動を使う",
    caution: "初心者には高負荷。肘や手首の痛みが出たら中止。",
    reps: "5〜10回",
    sets: 2,
    level: "中級",
  }),
  shoulderPress: g({
    aliases: ["ダンベルショルダープレス"],
    primary: "三角筋",
    secondary: "上腕三頭筋",
    setup: "背筋を伸ばして立つか座る。ダンベルを肩の横で構える。",
    movement: "頭上へ押し上げ、ゆっくり肩の位置まで戻す。",
    tips: "腰を反らさず、肋骨を開きすぎない。真上へ押す。",
    mistakes: "腰を反る／勢いを使う／下げすぎる",
    caution: "肩に痛みがある日は中止。",
    reps: "8〜12回",
    sets: 3,
    level: "初級",
  }),
  sideRaise: g({
    primary: "三角筋中部",
    secondary: "僧帽筋",
    setup: "腕を体側に下ろし、肘を軽く曲げる。",
    movement: "腕を横へ上げ、肩の高さ付近で止めてゆっくり下ろす。",
    tips: "肘から持ち上げる意識。肩をすくめない。軽い重量で丁寧に。",
    mistakes: "反動を使う／肩をすくめる／腕を高く上げすぎる",
    caution: "重すぎる重量は肩を痛めやすい。",
    reps: "10〜15回",
    sets: 3,
    level: "初級",
  }),
  frontRaise: g({
    primary: "三角筋前部",
    secondary: "大胸筋上部",
    setup: "ダンベルを太ももの前で持つ。",
    movement: "腕を前方へ肩の高さまで上げ、ゆっくり戻す。",
    tips: "腰を反らず、肘を軽く曲げたまま。",
    mistakes: "勢いで振り上げる／肩より高く上げる",
    caution: "前肩は他種目でも使うのでやりすぎ注意。",
    reps: "10〜15回",
    sets: 2,
    level: "初級",
  }),
  rearRaise: g({
    primary: "三角筋後部",
    secondary: "僧帽筋・菱形筋",
    setup: "股関節から上体を前傾し、背中をまっすぐ保つ。",
    movement: "腕を左右へ開いて肩甲骨周辺を収縮させる。",
    tips: "腕ではなく後ろ肩で開く。肩をすくめない。",
    mistakes: "腰が丸い／反動を使う／肘を引きすぎてロウになる",
    caution: "軽い重量でフォーム優先。",
    reps: "10〜15回",
    sets: 3,
    level: "中級",
  }),
  pikePushup: g({
    primary: "三角筋",
    secondary: "上腕三頭筋",
    setup: "四つ這いからお尻を高く上げ、体を逆V字にする。",
    movement: "頭を手と手の間へ下ろし、肩で押し戻す。",
    tips: "お尻を高く保ち、頭を前ではなく斜め下へ。",
    mistakes: "通常の腕立てのように前後へ動く／腰が落ちる",
    caution: "首を床へぶつけない。肩に痛みが出たら中止。",
    reps: "5〜12回",
    sets: 3,
    level: "中級",
  }),
  oneHandRow: g({
    aliases: ["ワンハンドダンベルロウ"],
    primary: "広背筋",
    secondary: "僧帽筋・上腕二頭筋・三角筋後部",
    setup: "片手を椅子や台に置き、背中を床とほぼ平行にする。",
    movement: "ダンベルを腰へ向けて引き、ゆっくり下ろす。",
    tips: "『手で持ち上げる』より『肘を後ろへ引く』意識。肩をすくめない。",
    mistakes: "体をひねる／肘が外へ開く／腕だけで引く",
    caution: "腰を丸めない。",
    reps: "8〜15回",
    sets: 3,
    level: "初級",
  }),
  dbBentRow: g({
    primary: "広背筋・僧帽筋",
    secondary: "上腕二頭筋・三角筋後部",
    setup: "両手にダンベル。膝を軽く曲げ、股関節から前傾する。",
    movement: "両肘を後方へ引いてダンベルを腹部へ近づける。",
    tips: "背中はまっすぐ。ダンベルを腹〜腰へ引く。",
    mistakes: "背中が丸い／上体を起こして反動を使う",
    caution: "腰に痛みが出るフォームは中止。",
    reps: "8〜15回",
    sets: 3,
    level: "中級",
  }),
  bbBentRow: g({
    primary: "広背筋・僧帽筋",
    secondary: "上腕二頭筋・三角筋後部",
    setup: "バーを肩幅程度で持ち、股関節から前傾。",
    movement: "バーを腹部へ引き、コントロールして下ろす。",
    tips: "胸を軽く張り、肘を後ろへ引く。",
    mistakes: "腰が丸い／反動で引く／首を反らす",
    caution: "連結部の緩みと重量バランスを確認。",
    reps: "8〜12回",
    sets: 3,
    level: "中級",
  }),
  rdl: g({
    primary: "ハムストリングス・大臀筋",
    secondary: "脊柱起立筋・前腕",
    setup: "足を腰幅にして重りを太ももの前に持つ。",
    movement: "膝を軽く曲げ、尻を後ろへ引きながら重りを下げ、尻を締めて立つ。",
    tips: "背中をまっすぐ保ち、膝ではなく股関節を曲げる。",
    mistakes: "背中が丸い／スクワットになる／重りが体から離れる",
    caution: "もも裏に鋭い痛みがある日はやらない。",
    reps: "8〜15回",
    sets: 3,
    level: "中級",
  }),
  dbCurl: g({
    primary: "上腕二頭筋",
    secondary: "前腕",
    setup: "背筋を伸ばし、腕を体側へ下ろす。手のひらは前向き。",
    movement: "肘を固定してダンベルを肩方向へ上げ、ゆっくり下ろす。",
    tips: "肘を動かさない。上で1秒収縮、下ろしは2〜3秒。",
    mistakes: "体を反る／肘が前へ出る／手首を曲げる",
    caution: "重さよりフォーム優先。",
    reps: "8〜15回",
    sets: 3,
    level: "初級",
  }),
  hammerCurl: g({
    primary: "上腕筋・腕橈骨筋",
    secondary: "上腕二頭筋・前腕",
    setup: "手のひらを体側へ向け、ダンベルを縦に持つ。",
    movement: "親指を上へ向けたまま肘を曲げ、ゆっくり戻す。",
    tips: "手首をまっすぐ。肘を体側で固定。",
    mistakes: "肩まで上げすぎる／体を振る／手首が折れる",
    caution: "左右差がある場合は弱い側に回数を合わせる。",
    reps: "8〜15回",
    sets: 3,
    level: "初級",
  }),
  bbCurl: g({
    primary: "上腕二頭筋",
    secondary: "前腕",
    setup: "バーを肩幅程度で逆手に持ち、肘を体側へ。",
    movement: "肘を固定してバーを上げ、ゆっくり下ろす。",
    tips: "腰を反らず、二頭筋で上げる。",
    mistakes: "反動／肘が前へ動く／重量過多",
    caution: "連結バーの固定を確認。",
    reps: "8〜12回",
    sets: 3,
    level: "中級",
  }),
  ohExtension: g({
    primary: "上腕三頭筋",
    secondary: "肩周辺",
    setup: "ダンベル1個を両手で持ち、頭上へ上げる。",
    movement: "肘を曲げて頭の後ろへ下ろし、肘を伸ばして戻す。",
    tips: "肘を前へ向けて幅を固定。上腕を動かしすぎない。",
    mistakes: "肘が外へ広がる／腰を反る",
    caution: "ダンベルを頭へ落とさないよう握りを確認。",
    reps: "8〜15回",
    sets: 3,
    level: "初級",
  }),
  narrowFloorPress: g({
    primary: "上腕三頭筋",
    secondary: "大胸筋",
    setup: "床に仰向け。手幅を狭めにして重りを胸上で保持。",
    movement: "肘を体側へ寄せて下ろし、押し上げる。",
    tips: "脇を締め、三頭筋で押す意識。",
    mistakes: "肘が外へ開く／手首が反る",
    caution: "肩や肘に違和感が出たら手幅を調整。",
    reps: "8〜12回",
    sets: 3,
    level: "中級",
  }),
  wristCurl: g({
    primary: "前腕屈筋群",
    secondary: "握力",
    setup: "前腕を太もも等に置き、手のひらを上へ。手首だけ外に出す。",
    movement: "手首を下げてから巻き上げる。",
    tips: "前腕を固定し、手首だけをゆっくり動かす。",
    mistakes: "肘まで動かす／反動／重量過多",
    caution: "小さい関節なので軽重量から。",
    reps: "12〜20回",
    sets: 2,
    level: "初級",
  }),
  reverseWristCurl: g({
    primary: "前腕伸筋群",
    secondary: "手首周辺",
    setup: "前腕を固定し、手の甲を上向きにする。",
    movement: "手首を下げてから反らすように上げる。",
    tips: "可動域を欲張らず丁寧に。",
    mistakes: "重すぎる／前腕が浮く",
    caution: "手首に痛みがあれば中止。",
    reps: "12〜20回",
    sets: 2,
    level: "初級",
  }),
  reverseCurl: g({
    primary: "腕橈骨筋・前腕伸筋群",
    secondary: "上腕二頭筋",
    setup: "手の甲を前に向ける順手で持つ。",
    movement: "肘を固定して重りを持ち上げる。",
    tips: "手首をまっすぐ保ち、軽めの重量で。",
    mistakes: "手首が曲がる／体を反る",
    caution: "通常カールより軽い重量を使う。",
    reps: "8〜15回",
    sets: 3,
    level: "中級",
  }),
  handgrip: g({
    primary: "前腕屈筋群・握力",
    secondary: "指の屈筋群",
    setup: "グリップを手のひら中央へ置き、手首をまっすぐ。",
    movement: "握り切ってからゆっくり開く。",
    tips: "速く連打せず、握り切る。",
    mistakes: "手首を曲げる／毎日高負荷で追い込む",
    caution: "腱や肘が痛い場合は休む。",
    reps: "10〜20回",
    sets: 2,
    level: "初級",
  }),
  dbHold: g({
    aliases: ["ダンベル保持（ファーマーズホールド）", "ファーマーズホールド"],
    primary: "握力・前腕",
    secondary: "僧帽筋・体幹",
    setup: "両手にダンベルを持ち、胸を張って直立。",
    movement: "姿勢を保ったまま一定時間握り続ける。",
    tips: "肩をすくめすぎず、手首を中立に。",
    mistakes: "猫背／手首が曲がる",
    caution: "落下に注意。足元を空ける。",
    reps: "20〜45秒",
    sets: 3,
    level: "初級",
  }),
  abRoller: g({
    aliases: ["腹筋ローラー（膝コロ）", "膝コロ"],
    primary: "腹直筋・腹横筋",
    secondary: "広背筋・肩・上腕三頭筋",
    setup: "膝を床につき、ローラーを肩の真下付近で持つ。",
    movement: "体を前へ伸ばし、腰が反る前に腹筋で引き戻す。",
    tips: "お腹を丸め気味に保ち、腰を反らさない。戻りは腕ではなく腹で。",
    mistakes: "腰が反る／遠くへ行きすぎる／腕だけで戻る",
    caution: "腰痛につながりやすい。可動域は短くてOK。",
    reps: "5〜10回",
    sets: 3,
    level: "中級",
  }),
  crunch: g({
    primary: "腹直筋",
    secondary: "腹斜筋",
    setup: "仰向けで膝を曲げ、腰を床へ。",
    movement: "肩甲骨が浮く程度まで上体を丸める。",
    tips: "みぞおちと骨盤を近づける意識。",
    mistakes: "首を引っ張る／完全に起き上がる",
    caution: "首に力を入れすぎない。",
    reps: "10〜20回",
    sets: 3,
    level: "初級",
  }),
  legRaise: g({
    primary: "腹直筋下部・腸腰筋",
    secondary: "体幹",
    setup: "仰向け。脚を伸ばし、腰を床へ押しつける。",
    movement: "脚を上げ、腰が反らない範囲までゆっくり下ろす。",
    tips: "腰を床から浮かせない。",
    mistakes: "脚を勢いで振る／腰が反る",
    caution: "腰が浮く場合は膝を曲げる。",
    reps: "8〜15回",
    sets: 3,
    level: "中級",
  }),
  plank: g({
    primary: "腹横筋・腹直筋",
    secondary: "肩・臀筋",
    setup: "肘とつま先で支え、頭から踵まで一直線。",
    movement: "姿勢を一定時間維持する。",
    tips: "腹と尻を締め、呼吸を止めない。",
    mistakes: "腰が落ちる／尻が上がりすぎる",
    caution: "腰痛が出る姿勢は中止。",
    reps: "20〜60秒",
    sets: 3,
    level: "初級",
  }),
  sidePlank: g({
    primary: "腹斜筋",
    secondary: "中臀筋・肩",
    setup: "横向きで肘を肩の真下へ置き、体を一直線。",
    movement: "腰を浮かせて姿勢を維持する。",
    tips: "骨盤を前後に倒さず一直線。",
    mistakes: "腰が落ちる／肩がすくむ",
    caution: "肩に痛みがある場合は短時間から。",
    reps: "20〜45秒/側",
    sets: 2,
    level: "初級",
  }),
  gobletSquat: g({
    primary: "大腿四頭筋・大臀筋",
    secondary: "ハムストリングス・体幹",
    setup: "ダンベル1個を胸前で持ち、足を肩幅程度に開く。",
    movement: "尻を後ろへ引きながらしゃがみ、床を押して立つ。",
    tips: "膝とつま先の向きを揃える。胸を落とさない。",
    mistakes: "膝が内側へ入る／踵が浮く／背中が丸い",
    caution: "痛みが出ない深さで。",
    reps: "8〜15回",
    sets: 3,
    level: "初級",
  }),
  dbSquat: g({
    primary: "大腿四頭筋・大臀筋",
    secondary: "ハムストリングス",
    setup: "両手にダンベルを持ち、体側へ下げる。",
    movement: "腰を落としてしゃがみ、立ち上がる。",
    tips: "足裏全体で床を押す。",
    mistakes: "膝が内側へ入る／前屈しすぎる",
    caution: "太もも裏が強く痛む日は休む。",
    reps: "8〜15回",
    sets: 3,
    level: "初級",
  }),
  bulgarian: g({
    primary: "大臀筋・大腿四頭筋",
    secondary: "ハムストリングス",
    setup: "後ろ足を椅子等へ乗せ、前足で体重を支える。",
    movement: "前脚の膝を曲げて腰を落とし、前脚で立つ。",
    tips: "前脚の踵に体重を乗せる。左右の骨盤を正面へ。",
    mistakes: "前足が近すぎる／膝が内側へ入る",
    caution: "バランスが不安なら自重から。",
    reps: "8〜12回/側",
    sets: 3,
    level: "中級",
  }),
  hipLift: g({
    primary: "大臀筋",
    secondary: "ハムストリングス",
    setup: "仰向けで膝を曲げ、足裏を床へ。ダンベルは骨盤上に置ける。",
    movement: "尻を締めながら骨盤を上げ、ゆっくり戻す。",
    tips: "腰を反るのではなく尻で持ち上げる。",
    mistakes: "腰を反る／膝が開きすぎる",
    caution: "ダンベル使用時は骨盤にタオルを挟むと楽。",
    reps: "12〜20回",
    sets: 3,
    level: "初級",
  }),
  calfRaise: g({
    primary: "下腿三頭筋（ふくらはぎ）",
    secondary: "足部",
    setup: "まっすぐ立ち、必要なら壁に手を添える。",
    movement: "踵を高く上げ、ゆっくり下ろす。",
    tips: "一番上で1秒止める。",
    mistakes: "反動で上下する／足首が外へ逃げる",
    caution: "段差使用時はバランスに注意。",
    reps: "15〜25回",
    sets: 3,
    level: "初級",
  }),
};

/** 全種目共通のポイント（一覧表「使い方」シート） */
export const FORM_BASICS: { label: string; text: string }[] = [
  { label: "重量設定", text: "最後の2〜3回がきついがフォームは崩れない重量を目安にする。" },
  { label: "休憩", text: "通常60〜90秒。高負荷種目は90〜120秒でも可。" },
  { label: "痛みの判断", text: "筋肉の張り・だるさは一般的だが、鋭い痛み・関節痛・しびれがあれば中止。" },
  { label: "進め方", text: "回数上限を余裕でこなせるようになったら、重量・回数・セット・テンポのいずれかを少し上げる。" },
];
